"""SentinEL configuration loaded from environment variables."""

from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

_ENV_PATH = Path(__file__).resolve().parent / ".env"
load_dotenv(_ENV_PATH)

# WhisperX → pyannote → speechbrain: Windows k2_fsa lazy-import crash guard
try:
    from utils.speechbrain_patch import apply_speechbrain_windows_patch

    apply_speechbrain_windows_patch()
except Exception:
    pass


def _require(name: str) -> str:
    value = os.getenv(name)
    if not value:
        raise ValueError(f"Missing required environment variable: {name}")
    return value


def _get_float(name: str, default: float) -> float:
    raw = os.getenv(name)
    if raw is None or raw.strip() == "":
        return default
    return float(raw)


def _get_str(name: str, default: str) -> str:
    return os.getenv(name, default).strip() or default


# --- Secrets & endpoints ---
HF_TOKEN: str = _require("HF_TOKEN")

# Optional override for CLI / web launcher
SENTINEL_PYTHON: str = os.getenv("SENTINEL_PYTHON", "").strip()

# Remove or leave blank — not used in local CPU mode
KAGGLE_GPU_URL: str = os.getenv("KAGGLE_GPU_URL", "").strip()
SENTINEL_SECRET: str = (
    os.getenv("SENTINEL_SECRET", "").strip()
    or os.getenv("KAGGLE_SECRET", "").strip()
)
KAGGLE_GPU_TIMEOUT_SEC: int = int(_get_float("KAGGLE_GPU_TIMEOUT_SEC", 180))

# --- Tunable detection parameters ---
ALERT_THRESHOLD: float = _get_float("ALERT_THRESHOLD", 0.55)
STD_FLOOR: float = _get_float("STD_FLOOR", 0.05)
EWMA_ALPHA_ATTACK: float = _get_float("EWMA_ALPHA_ATTACK", 0.75)
EWMA_ALPHA_DECAY: float = _get_float("EWMA_ALPHA_DECAY", 0.15)

# ── Whisper model size guide ──────────────────────────────────────
# tiny   : ~1s/answer  · lowest accuracy · good for quick testing
# base   : ~2s/answer  · low accuracy    · okay for testing
# small  : ~4s/answer  · good accuracy   · RECOMMENDED for CPU
# medium : ~10s/answer · better accuracy · use if small misses fillers
# large-v3: too slow on CPU without GPU  · use Kaggle notebook instead
# ─────────────────────────────────────────────────────────────────

# Whisper settings — optimised for CPU with int8 quantization
WHISPER_MODEL_SIZE: str = _get_str("WHISPER_MODEL_SIZE", "small")
WHISPER_DEVICE: str = _get_str("WHISPER_DEVICE", "cpu")
WHISPER_COMPUTE_TYPE: str = _get_str("WHISPER_COMPUTE_TYPE", "int8")

# --- Feature weights (normalised to sum to 1.0 in FusedScorer) ---
WEIGHT_ACOUSTIC: float = _get_float("WEIGHT_ACOUSTIC", 0.2625)
WEIGHT_LINGUISTIC: float = _get_float("WEIGHT_LINGUISTIC", 0.2625)
WEIGHT_GAZE: float = _get_float("WEIGHT_GAZE", 0.2625)
WEIGHT_LIP: float = _get_float("WEIGHT_LIP", 0.2125)

# --- Dual-profile contrastive engine (v5) ---
ENABLE_CONTRASTIVE_ENGINE: bool = os.getenv("ENABLE_CONTRASTIVE_ENGINE", "true").lower() in (
    "1",
    "true",
    "yes",
)
ENABLE_DYNAMIC_NATURAL_PROFILE: bool = os.getenv(
    "ENABLE_DYNAMIC_NATURAL_PROFILE", "true"
).lower() in ("1", "true", "yes")

NATURAL_PROFILE_MIN_SAMPLES: int = int(_get_float("NATURAL_PROFILE_MIN_SAMPLES", 2))
PROFILE_MAX_SAMPLES_PER_METRIC: int = int(_get_float("PROFILE_MAX_SAMPLES_PER_METRIC", 500))
TRANSITION_ALERT_THRESHOLD: float = _get_float("TRANSITION_ALERT_THRESHOLD", 0.5)
MIN_ANSWER_SEC_FOR_HIGH: float = _get_float("MIN_ANSWER_SEC_FOR_HIGH", 8.0)
PAUSE_ENTROPY_NORM: float = _get_float("PAUSE_ENTROPY_NORM", 2.5)

# --- Scoring calibration (false-positive reduction) ---
# Legacy label; profile learning uses NATURALITY_LEARNING_THRESHOLD (stricter)
NATURALITY_UPDATE_THRESHOLD: float = _get_float("NATURALITY_UPDATE_THRESHOLD", 0.38)
NATURAL_UPDATE_FLUENT_SCRIPT_CEILING: float = _get_float(
    "NATURAL_UPDATE_FLUENT_SCRIPT_CEILING", 0.52
)

# NATURAL similarity saturation control
NATURAL_SIMILARITY_CAP: float = _get_float("NATURAL_SIMILARITY_CAP", 0.82)
NATURAL_PROFILE_CONFIDENCE_FLOOR: float = _get_float("NATURAL_PROFILE_CONFIDENCE_FLOOR", 0.38)

# --- NATURAL profile purity / anti-dilution ---
# Scoring uses naturality_score; profile learning uses stricter naturality_for_learning
NATURALITY_LEARNING_THRESHOLD: float = _get_float("NATURALITY_LEARNING_THRESHOLD", 0.52)
NATURAL_UPDATE_MAX_SCRIPT_SIM: float = _get_float("NATURAL_UPDATE_MAX_SCRIPT_SIM", 0.55)
NATURAL_UPDATE_MIN_SPONTANEITY_SIGNALS: int = int(
    _get_float("NATURAL_UPDATE_MIN_SPONTANEITY_SIGNALS", 4)
)
NATURAL_UPDATE_MIN_STRONG_CATEGORIES: int = int(
    _get_float("NATURAL_UPDATE_MIN_STRONG_CATEGORIES", 3)
)
NATURAL_UPDATE_MIN_PAUSE_ENTROPY: float = _get_float("NATURAL_UPDATE_MIN_PAUSE_ENTROPY", 0.65)
NATURAL_UPDATE_MAX_TECHNICAL_DENSITY: float = _get_float(
    "NATURAL_UPDATE_MAX_TECHNICAL_DENSITY", 0.12
)
NATURAL_UPDATE_TECHNICAL_EXTRA_STRONG: int = int(
    _get_float("NATURAL_UPDATE_TECHNICAL_EXTRA_STRONG", 1)
)
NATURAL_PROFILE_MAX_STORED_SAMPLES: int = int(
    _get_float("NATURAL_PROFILE_MAX_STORED_SAMPLES", 36)
)
NATURAL_PROFILE_MAX_SAMPLES_PER_METRIC: int = int(
    _get_float("NATURAL_PROFILE_MAX_SAMPLES_PER_METRIC", 48)
)
NATURAL_PROFILE_MIN_LEARNING_CONFIDENCE: float = _get_float(
    "NATURAL_PROFILE_MIN_LEARNING_CONFIDENCE", 0.62
)
NATURAL_PROFILE_DIVERSITY_MIN_DISTANCE: float = _get_float(
    "NATURAL_PROFILE_DIVERSITY_MIN_DISTANCE", 0.08
)
NATURAL_PROFILE_SAMPLE_MAX_AGE_ANSWERS: int = int(
    _get_float("NATURAL_PROFILE_SAMPLE_MAX_AGE_ANSWERS", 8)
)
NATURAL_PROFILE_FORGET_LOW_CONF_AGE: int = int(
    _get_float("NATURAL_PROFILE_FORGET_LOW_CONF_AGE", 4)
)
NATURAL_SIMILARITY_SATURATION_WINDOW: int = int(
    _get_float("NATURAL_SIMILARITY_SATURATION_WINDOW", 24)
)
NATURAL_SIMILARITY_SATURATION_MEAN: float = _get_float(
    "NATURAL_SIMILARITY_SATURATION_MEAN", 0.72
)
NATURAL_SIMILARITY_SATURATION_PENALTY: float = _get_float(
    "NATURAL_SIMILARITY_SATURATION_PENALTY", 0.18
)
NATURAL_PROFILE_PURITY_COLLAPSE: float = _get_float("NATURAL_PROFILE_PURITY_COLLAPSE", 0.42)
NATURAL_PROFILE_UPDATE_RATE_WARN: float = _get_float(
    "NATURAL_PROFILE_UPDATE_RATE_WARN", 0.35
)

# Script dominance override (recall recovery)
SCRIPT_DOMINANCE_THRESHOLD: float = _get_float("SCRIPT_DOMINANCE_THRESHOLD", 0.70)
SCRIPT_DOMINANCE_MIN_WINDOWS: int = int(_get_float("SCRIPT_DOMINANCE_MIN_WINDOWS", 3))
SCRIPT_DOMINANCE_BOOST: float = _get_float("SCRIPT_DOMINANCE_BOOST", 0.16)
SCRIPT_DOMINANCE_MAX_SUPPRESSION: float = _get_float("SCRIPT_DOMINANCE_MAX_SUPPRESSION", 0.10)
PER_WINDOW_SCRIPT_BOOST: float = _get_float("PER_WINDOW_SCRIPT_BOOST", 0.04)
SCRIPT_NATURAL_COLLAPSE_BOOST: float = _get_float("SCRIPT_NATURAL_COLLAPSE_BOOST", 0.08)

# Long-horizon consistency (20–40s)
LONG_HORIZON_MIN_SEC: float = _get_float("LONG_HORIZON_MIN_SEC", 20.0)
LOW_DRIFT_SUSPICION_THRESHOLD: float = _get_float("LOW_DRIFT_SUSPICION_THRESHOLD", 0.58)
LOW_DRIFT_BOOST: float = _get_float("LOW_DRIFT_BOOST", 0.10)
CLEANLINESS_SUSPICION_THRESHOLD: float = _get_float("CLEANLINESS_SUSPICION_THRESHOLD", 0.62)
CLEANLINESS_BOOST: float = _get_float("CLEANLINESS_BOOST", 0.08)
FAKE_NATURALITY_THRESHOLD: float = _get_float("FAKE_NATURALITY_THRESHOLD", 0.55)
FAKE_NATURALITY_BOOST: float = _get_float("FAKE_NATURALITY_BOOST", 0.07)
FAKE_NATURALITY_MAX_SUPPRESSION: float = _get_float("FAKE_NATURALITY_MAX_SUPPRESSION", 0.08)
ANSWER_CONTRASTIVE_FLOOR_MAX: float = _get_float("ANSWER_CONTRASTIVE_FLOOR_MAX", 0.22)
ANSWER_FLOOR_SCALE: float = _get_float("ANSWER_FLOOR_SCALE", 0.85)

# Sustained moderate suspicion → gradual EWMA climb
SUSTAINED_MODERATE_RATIO: float = _get_float("SUSTAINED_MODERATE_RATIO", 0.40)
SUSTAINED_EWMA_BOOST_PER_WINDOW: float = _get_float("SUSTAINED_EWMA_BOOST_PER_WINDOW", 0.025)

# --- Third-pass: modulated scoring + asymmetric temporal aggregation ---
STRONG_SCRIPT_THRESHOLD: float = _get_float("STRONG_SCRIPT_THRESHOLD", 0.68)
STRONG_SCRIPT_NONLINEAR_GAIN: float = _get_float("STRONG_SCRIPT_NONLINEAR_GAIN", 0.22)
STRONG_SCRIPT_NONLINEAR_POWER: float = _get_float("STRONG_SCRIPT_NONLINEAR_POWER", 1.6)
SPONTANEITY_MODULATION_WEIGHT: float = _get_float("SPONTANEITY_MODULATION_WEIGHT", 0.42)
SPONTANEITY_MODULATION_FLOOR: float = _get_float("SPONTANEITY_MODULATION_FLOOR", 0.55)
STRONG_SCRIPT_MAX_SPONT_REDUCTION: float = _get_float("STRONG_SCRIPT_MAX_SPONT_REDUCTION", 0.28)
MODERATE_SCRIPT_MAX_SPONT_REDUCTION: float = _get_float("MODERATE_SCRIPT_MAX_SPONT_REDUCTION", 0.42)
WEAK_SCRIPT_MAX_SPONT_REDUCTION: float = _get_float("WEAK_SCRIPT_MAX_SPONT_REDUCTION", 0.55)
FAKE_NATURALITY_MODULATION_PENALTY: float = _get_float("FAKE_NATURALITY_MODULATION_PENALTY", 0.35)
STRONG_WINDOW_WEIGHT_BONUS: float = _get_float("STRONG_WINDOW_WEIGHT_BONUS", 0.55)
PEAK_EWMA_BLEND: float = _get_float("PEAK_EWMA_BLEND", 0.72)
P90_WINDOW_BLEND: float = _get_float("P90_WINDOW_BLEND", 0.55)
STRONG_MEAN_BLEND: float = _get_float("STRONG_MEAN_BLEND", 0.48)
SUSTAINED_STRONG_SCRIPT_FLOOR_RATIO: float = _get_float("SUSTAINED_STRONG_SCRIPT_FLOOR_RATIO", 0.92)
EWMA_BENIGN_SCRIPTED_MULTIPLIER: float = _get_float("EWMA_BENIGN_SCRIPTED_MULTIPLIER", 0.88)
EWMA_STRONG_SCRIPT_ATTACK_ALPHA: float = _get_float("EWMA_STRONG_SCRIPT_ATTACK_ALPHA", 0.88)
HIGH_CONFIDENCE_MIN_STRONG_RATIO: float = _get_float("HIGH_CONFIDENCE_MIN_STRONG_RATIO", 0.35)
PERSISTENCE_STRONG_RATIO_FALLBACK: float = _get_float("PERSISTENCE_STRONG_RATIO_FALLBACK", 0.55)

# --- Suspicion calibration tiers (fourth-pass FP stabilization) ---
SUSPICION_TIER_WEAK: float = _get_float("SUSPICION_TIER_WEAK", 0.15)
SUSPICION_TIER_MODERATE: float = _get_float("SUSPICION_TIER_MODERATE", 0.25)
SUSPICION_TIER_STRONG: float = _get_float("SUSPICION_TIER_STRONG", 0.35)
SUSPICION_SCRIPT_BUMP_MIN: float = _get_float("SUSPICION_SCRIPT_BUMP_MIN", 0.18)
SUSPICION_WEIGHT_WEAK: float = _get_float("SUSPICION_WEIGHT_WEAK", 0.5)
SUSPICION_WEIGHT_MODERATE: float = _get_float("SUSPICION_WEIGHT_MODERATE", 1.0)
SUSPICION_WEIGHT_STRONG: float = _get_float("SUSPICION_WEIGHT_STRONG", 2.0)
SUSPICION_NONLINEAR_POWER: float = _get_float("SUSPICION_NONLINEAR_POWER", 1.35)
SUSPICION_STRONG_SCRIPT_FACTOR: float = _get_float("SUSPICION_STRONG_SCRIPT_FACTOR", 0.35)
SUSPICION_EVIDENCE_NORM: float = _get_float("SUSPICION_EVIDENCE_NORM", 5.0)
EVIDENCE_COMPOSITE_SCALE: float = _get_float("EVIDENCE_COMPOSITE_SCALE", 1.15)
COMPOSITE_EWMA_BLEND: float = _get_float("COMPOSITE_EWMA_BLEND", 0.55)
EWMA_WEAK_INPUT_SCALE: float = _get_float("EWMA_WEAK_INPUT_SCALE", 0.35)
EWMA_MODERATE_INPUT_SCALE: float = _get_float("EWMA_MODERATE_INPUT_SCALE", 0.65)
EWMA_STRONG_INPUT_SCALE: float = _get_float("EWMA_STRONG_INPUT_SCALE", 1.0)
EWMA_WEAK_DECAY_MULTIPLIER: float = _get_float("EWMA_WEAK_DECAY_MULTIPLIER", 0.72)
WEAK_SUSPICION_NATURALITY_CAP: float = _get_float("WEAK_SUSPICION_NATURALITY_CAP", 0.62)
WEAK_SUSPICION_NATURAL_SIM_CAP: float = _get_float("WEAK_SUSPICION_NATURAL_SIM_CAP", 0.55)
PROBABLE_MIN_WEIGHTED_EVIDENCE: float = _get_float("PROBABLE_MIN_WEIGHTED_EVIDENCE", 2.75)
PROBABLE_MIN_STRONG_RATIO: float = _get_float("PROBABLE_MIN_STRONG_RATIO", 0.22)
PROBABLE_MIN_CONSECUTIVE_STRONG: int = int(_get_float("PROBABLE_MIN_CONSECUTIVE_STRONG", 2))
PROBABLE_MIN_COMPOSITE_RATIO: float = _get_float("PROBABLE_MIN_COMPOSITE_RATIO", 0.95)
HIGH_MIN_WEIGHTED_EVIDENCE: float = _get_float("HIGH_MIN_WEIGHTED_EVIDENCE", 5.5)
AMBIGUOUS_MIN_WEIGHTED_EVIDENCE: float = _get_float("AMBIGUOUS_MIN_WEIGHTED_EVIDENCE", 1.2)
WEAK_CLUSTER_MIN_RATIO: float = _get_float("WEAK_CLUSTER_MIN_RATIO", 0.55)
WEAK_CLUSTER_MIN_STREAK: int = int(_get_float("WEAK_CLUSTER_MIN_STREAK", 3))
WEAK_CLUSTER_MIN_AVG_SCRIPT_SIM: float = _get_float("WEAK_CLUSTER_MIN_AVG_SCRIPT_SIM", 0.58)
WEAK_CLUSTER_AMBIGUOUS_COMPOSITE_RATIO: float = _get_float(
    "WEAK_CLUSTER_AMBIGUOUS_COMPOSITE_RATIO", 0.72
)
WEAK_CLUSTER_PROBABLE_COMPOSITE_RATIO: float = _get_float(
    "WEAK_CLUSTER_PROBABLE_COMPOSITE_RATIO", 0.88
)
WEAK_CLUSTER_PROBABLE_MIN_MOMENTUM: float = _get_float(
    "WEAK_CLUSTER_PROBABLE_MIN_MOMENTUM", 0.48
)

# --- Temporal persistence (momentum + context-aware decay) ---
MOMENTUM_LOOKBACK_WINDOWS: int = int(_get_float("MOMENTUM_LOOKBACK_WINDOWS", 6))
MOMENTUM_DENSITY_NORM: float = _get_float("MOMENTUM_DENSITY_NORM", 0.75)
MOMENTUM_STREAK_NORM: float = _get_float("MOMENTUM_STREAK_NORM", 4)
MOMENTUM_HIGH_THRESHOLD: float = _get_float("MOMENTUM_HIGH_THRESHOLD", 0.55)
MOMENTUM_MED_THRESHOLD: float = _get_float("MOMENTUM_MED_THRESHOLD", 0.32)
EWMA_DECAY_LOW_DENSITY: float = _get_float("EWMA_DECAY_LOW_DENSITY", 0.55)
EWMA_DECAY_MOMENTUM_HIGH: float = _get_float("EWMA_DECAY_MOMENTUM_HIGH", 0.88)
EWMA_DECAY_MOMENTUM_MED: float = _get_float("EWMA_DECAY_MOMENTUM_MED", 0.78)
PEAK_EWMA_MOMENTUM_BLEND: float = _get_float("PEAK_EWMA_MOMENTUM_BLEND", 0.82)
STREAK_BOOST_PER_STRONG: float = _get_float("STREAK_BOOST_PER_STRONG", 0.018)
STREAK_BOOST_MAX_WINDOWS: int = int(_get_float("STREAK_BOOST_MAX_WINDOWS", 5))
STREAK_BOOST_STRONG_COUNT_BONUS: float = _get_float("STREAK_BOOST_STRONG_COUNT_BONUS", 0.04)
PROBABLE_LIFETIME_STRONG_RATIO: float = _get_float("PROBABLE_LIFETIME_STRONG_RATIO", 0.18)
PROBABLE_LONGEST_STREAK_MIN: int = int(_get_float("PROBABLE_LONGEST_STREAK_MIN", 2))
PROBABLE_PEAK_EWMA_RATIO: float = _get_float("PROBABLE_PEAK_EWMA_RATIO", 0.75)

# --- Answer-level behavioral synthesis (Layer 3 — final authority) ---
DOMINANT_SCRIPT_READING_THRESHOLD: float = _get_float(
    "DOMINANT_SCRIPT_READING_THRESHOLD", 0.52
)
DOMINANT_HIGH_CONFIDENCE_THRESHOLD: float = _get_float(
    "DOMINANT_HIGH_CONFIDENCE_THRESHOLD", 0.68
)
DOMINANT_AMBIGUOUS_CEILING: float = _get_float("DOMINANT_AMBIGUOUS_CEILING", 0.38)
DOMINANT_MIN_STRONG_WINDOWS: int = int(_get_float("DOMINANT_MIN_STRONG_WINDOWS", 2))
DOMINANT_MIN_PEAK_SUSPICION: float = _get_float("DOMINANT_MIN_PEAK_SUSPICION", 0.36)
DOMINANT_MIN_SUSPICIOUS_DENSITY: float = _get_float(
    "DOMINANT_MIN_SUSPICIOUS_DENSITY", 0.42
)
DOMINANT_MAX_RECOVERY_STRENGTH: float = _get_float(
    "DOMINANT_MAX_RECOVERY_STRENGTH", 0.48
)
PEAK_SUSPICION_AUTHORITY: float = _get_float("PEAK_SUSPICION_AUTHORITY", 0.40)
STRONG_RECOVERY_THRESHOLD: float = _get_float("STRONG_RECOVERY_THRESHOLD", 0.62)

# Weighted contrastive (legacy subtractive weights; v3 uses modulation in scoring_v3.py)
CONTRASTIVE_SCRIPT_WEIGHT: float = _get_float("CONTRASTIVE_SCRIPT_WEIGHT", 0.65)
CONTRASTIVE_NATURAL_WEIGHT: float = _get_float("CONTRASTIVE_NATURAL_WEIGHT", 0.35)
SPONTANEITY_SUPPRESSION_SCALE: float = _get_float("SPONTANEITY_SUPPRESSION_SCALE", 0.25)
TECHNICAL_FLUENCY_DAMPENING: float = _get_float("TECHNICAL_FLUENCY_DAMPENING", 0.15)

# --- Contrastive separation recovery (dynamic range) ---
CONTRASTIVE_NONLINEAR_AMP: float = _get_float("CONTRASTIVE_NONLINEAR_AMP", 0.35)
CONTRASTIVE_NONLINEAR_POWER: float = _get_float("CONTRASTIVE_NONLINEAR_POWER", 1.6)
SUPPRESSION_SOFTENING_AT_HIGH_SCRIPT: float = _get_float(
    "SUPPRESSION_SOFTENING_AT_HIGH_SCRIPT", 0.25
)

# Relative dominance: script_similarity / natural_similarity
DOMINANCE_RATIO_MIN: float = _get_float("DOMINANCE_RATIO_MIN", 1.22)
DOMINANCE_RATIO_BOOST_PER_UNIT: float = _get_float(
    "DOMINANCE_RATIO_BOOST_PER_UNIT", 0.045
)
DOMINANCE_RATIO_MAX_BOOST: float = _get_float("DOMINANCE_RATIO_MAX_BOOST", 0.09)

# Naturality score shaping
NATURALITY_SIGMOID_CENTER: float = _get_float("NATURALITY_SIGMOID_CENTER", 0.32)
NATURALITY_SIGMOID_STEEPNESS: float = _get_float("NATURALITY_SIGMOID_STEEPNESS", 5.0)
NATURALITY_NO_WORDS_FLOOR: float = _get_float("NATURALITY_NO_WORDS_FLOOR", 0.28)
NATURAL_SIMILARITY_MATURITY_FLOOR: float = _get_float("NATURAL_SIMILARITY_MATURITY_FLOOR", 0.35)

# Acoustic channel dampening (1.0 = unchanged; 0.75 = 25% less suspicious)
ACOUSTIC_SENSITIVITY_SCALE: float = _get_float("ACOUSTIC_SENSITIVITY_SCALE", 0.78)
ACOUSTIC_SHORT_ANSWER_SEC: float = _get_float("ACOUSTIC_SHORT_ANSWER_SEC", 12.0)
ACOUSTIC_SHORT_ANSWER_EXTRA_SCALE: float = _get_float("ACOUSTIC_SHORT_ANSWER_EXTRA_SCALE", 0.9)

# --- Duration-aware temporal evidence normalization (answer-level) ---
# Short answers have fewer windows and higher variance; require stronger evidence.
TEMPORAL_SHORT_ANSWER_SEC: float = _get_float("TEMPORAL_SHORT_ANSWER_SEC", 12.0)
TEMPORAL_SHORT_MIN_WINDOWS: int = int(_get_float("TEMPORAL_SHORT_MIN_WINDOWS", 4))
TEMPORAL_SHORT_SUPPRESSION_MAX: float = _get_float(
    "TEMPORAL_SHORT_SUPPRESSION_MAX", 0.35
)

# Persistent-weak suspicion promotion (clever scripted delivery)
PERSISTENT_WEAK_MIN_DURATION_SEC: float = _get_float(
    "PERSISTENT_WEAK_MIN_DURATION_SEC", 18.0
)
PERSISTENT_WEAK_COVERAGE_MIN: float = _get_float("PERSISTENT_WEAK_COVERAGE_MIN", 0.55)
PERSISTENT_SUSPICIOUS_COVERAGE_MIN: float = _get_float(
    "PERSISTENT_SUSPICIOUS_COVERAGE_MIN", 0.68
)
PERSISTENT_WEAK_VARIANCE_MAX: float = _get_float("PERSISTENT_WEAK_VARIANCE_MAX", 0.012)
PERSISTENT_WEAK_RECOVERY_MAX: float = _get_float("PERSISTENT_WEAK_RECOVERY_MAX", 0.45)
PERSISTENT_WEAK_AVG_SCRIPT_MIN: float = _get_float("PERSISTENT_WEAK_AVG_SCRIPT_MIN", 0.60)
PERSISTENT_WEAK_BOOST_MAX: float = _get_float("PERSISTENT_WEAK_BOOST_MAX", 0.10)
PERSISTENT_WEAK_COMPOSITE_BONUS_MAX: float = _get_float(
    "PERSISTENT_WEAK_COMPOSITE_BONUS_MAX", 0.18
)
PERSISTENT_WEAK_CONSISTENCY_MIN: float = _get_float("PERSISTENT_WEAK_CONSISTENCY_MIN", 0.58)
PERSISTENT_WEAK_MIN_WINDOWS: int = int(_get_float("PERSISTENT_WEAK_MIN_WINDOWS", 4))
PERSISTENT_WEAK_MIN_STREAK: int = int(_get_float("PERSISTENT_WEAK_MIN_STREAK", 3))
PERSISTENT_WEAK_MEAN_FLOOR: float = _get_float("PERSISTENT_WEAK_MEAN_FLOOR", 0.16)
PERSISTENT_WEAK_MEAN_SPAN: float = _get_float("PERSISTENT_WEAK_MEAN_SPAN", 0.08)
PERSISTENT_WEAK_STABILITY_STD_NORM: float = _get_float(
    "PERSISTENT_WEAK_STABILITY_STD_NORM", 0.06
)
PERSISTENT_WEAK_RELIABILITY_EVIDENCE_SCALE: float = _get_float(
    "PERSISTENT_WEAK_RELIABILITY_EVIDENCE_SCALE", 2.8
)
PERSISTENT_WEAK_AUTHORITY_COMPOSITE_FLOOR: float = _get_float(
    "PERSISTENT_WEAK_AUTHORITY_COMPOSITE_FLOOR", 0.155
)
SHORT_ANSWER_AMBIGUOUS_MIN_MODERATE_WINDOWS: int = int(
    _get_float("SHORT_ANSWER_AMBIGUOUS_MIN_MODERATE_WINDOWS", 3)
)
SHORT_ANSWER_AMBIGUOUS_COMPOSITE_RATIO: float = _get_float(
    "SHORT_ANSWER_AMBIGUOUS_COMPOSITE_RATIO", 1.05
)
SHORT_ANSWER_AMBIGUOUS_MIN_PEAK: float = _get_float(
    "SHORT_ANSWER_AMBIGUOUS_MIN_PEAK", 0.30
)

# Consistency authority — flat low-variance suspicious flow (Answer 5 / adaptive fake spontaneity)
CONSISTENCY_MIN_DURATION_SEC: float = _get_float("CONSISTENCY_MIN_DURATION_SEC", 18.0)
CONSISTENCY_AUTHORITY_MIN_SCORE: float = _get_float("CONSISTENCY_AUTHORITY_MIN_SCORE", 0.58)
CONSISTENCY_MIN_ELEVATED_RATIO: float = _get_float("CONSISTENCY_MIN_ELEVATED_RATIO", 0.68)
CONSISTENCY_FLAT_STD_MAX: float = _get_float("CONSISTENCY_FLAT_STD_MAX", 0.028)
CONSISTENCY_MAX_RECOVERY_STRENGTH: float = _get_float("CONSISTENCY_MAX_RECOVERY_STRENGTH", 0.38)
CONSISTENCY_MAX_RECOVERY_FREQUENCY: float = _get_float("CONSISTENCY_MAX_RECOVERY_FREQUENCY", 0.18)
CONSISTENCY_AUTHORITY_COMPOSITE_BOOST: float = _get_float(
    "CONSISTENCY_AUTHORITY_COMPOSITE_BOOST", 0.14
)
CONSISTENCY_AUTHORITY_EVIDENCE_BOOST: float = _get_float(
    "CONSISTENCY_AUTHORITY_EVIDENCE_BOOST", 1.6
)
CONSISTENCY_BREATHING_DIP_THRESHOLD: float = _get_float(
    "CONSISTENCY_BREATHING_DIP_THRESHOLD", 0.11
)
CONSISTENCY_BREATHING_RANGE_MIN: float = _get_float("CONSISTENCY_BREATHING_RANGE_MIN", 0.08)
CONSISTENCY_BREATHING_MIN_SCORE: float = _get_float("CONSISTENCY_BREATHING_MIN_SCORE", 0.22)

# EWMA: stronger pull-down on benign windows
EWMA_BENIGN_MULTIPLIER: float = _get_float("EWMA_BENIGN_MULTIPLIER", 0.6)
EWMA_BENIGN_NATURALITY_MIN: float = _get_float("EWMA_BENIGN_NATURALITY_MIN", 0.35)

# Profile health
PROFILE_COLLAPSE_DISTANCE: float = _get_float("PROFILE_COLLAPSE_DISTANCE", 0.15)

# Alert thresholds (slightly stricter)
CONTRASTIVE_MARGIN: float = _get_float("CONTRASTIVE_MARGIN", 0.14)
PERSISTENCE_MIN_WINDOWS: int = int(_get_float("PERSISTENCE_MIN_WINDOWS", 3))
AMBIGUOUS_EWMA_RATIO: float = _get_float("AMBIGUOUS_EWMA_RATIO", 0.55)

# --- Performance / fast calibration ---
def _get_bool(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None or raw.strip() == "":
        return default
    return raw.strip().lower() in ("1", "true", "yes", "on")


# --- Cognitive spontaneity vs guided explanation ---
ENABLE_COGNITIVE_SPONTANEITY: bool = _get_bool("ENABLE_COGNITIVE_SPONTANEITY", True)
COGNITIVE_SPONTANEITY_SUPPRESSION_WEIGHT: float = _get_float(
    "COGNITIVE_SPONTANEITY_SUPPRESSION_WEIGHT", 0.22
)
COGNITIVE_REPAIR_SUPPRESSION_WEIGHT: float = _get_float(
    "COGNITIVE_REPAIR_SUPPRESSION_WEIGHT", 0.14
)
COGNITIVE_MAX_EXTRA_SUPPRESSION: float = _get_float("COGNITIVE_MAX_EXTRA_SUPPRESSION", 0.28)
COGNITIVE_GUIDED_BOOST_MIN: float = _get_float("COGNITIVE_GUIDED_BOOST_MIN", 0.52)
COGNITIVE_GUIDED_BOOST_SCALE: float = _get_float("COGNITIVE_GUIDED_BOOST_SCALE", 0.12)
COGNITIVE_GUIDED_MAX_BOOST: float = _get_float("COGNITIVE_GUIDED_MAX_BOOST", 0.10)
COGNITIVE_GUIDED_HIGH_THRESHOLD: float = _get_float("COGNITIVE_GUIDED_HIGH_THRESHOLD", 0.58)
COGNITIVE_NATURALITY_BLEND: float = _get_float("COGNITIVE_NATURALITY_BLEND", 0.18)
COGNITIVE_SCRIPT_DAMPEN_AT_SPONTANEITY: float = _get_float(
    "COGNITIVE_SCRIPT_DAMPEN_AT_SPONTANEITY", 0.20
)
COGNITIVE_FLUENCY_TRAP_BOOST: float = _get_float("COGNITIVE_FLUENCY_TRAP_BOOST", 0.08)
FLUENT_NATURAL_SPONTANEITY_FLOOR: float = _get_float("FLUENT_NATURAL_SPONTANEITY_FLOOR", 0.50)
FLUENT_LINGUISTIC_DAMPEN: float = _get_float("FLUENT_LINGUISTIC_DAMPEN", 0.22)
COGNITIVE_CLEAR_SPONTANEITY_MIN: float = _get_float("COGNITIVE_CLEAR_SPONTANEITY_MIN", 0.48)
COGNITIVE_CLEAR_GUIDED_MAX: float = _get_float("COGNITIVE_CLEAR_GUIDED_MAX", 0.45)
WEAK_SUSPICION_COGNITIVE_SPONTANEITY_CAP: float = _get_float(
    "WEAK_SUSPICION_COGNITIVE_SPONTANEITY_CAP", 0.55
)

# --- SCRIPT profile purification / profile disentanglement ---
SCRIPT_PROFILE_PURIFY_CALIBRATION: bool = _get_bool("SCRIPT_PROFILE_PURIFY_CALIBRATION", True)
SCRIPT_COGNITIVE_METRIC_WEIGHT: float = _get_float("SCRIPT_COGNITIVE_METRIC_WEIGHT", 1.0)
SCRIPT_LINGUISTIC_DELIVERY_WEIGHT: float = _get_float("SCRIPT_LINGUISTIC_DELIVERY_WEIGHT", 0.32)
SCRIPT_ACOUSTIC_DELIVERY_WEIGHT: float = _get_float("SCRIPT_ACOUSTIC_DELIVERY_WEIGHT", 0.24)
SCRIPT_STYLE_METRIC_WEIGHT: float = _get_float("SCRIPT_STYLE_METRIC_WEIGHT", 1.0)
NATURAL_COGNITIVE_METRIC_WEIGHT: float = _get_float("NATURAL_COGNITIVE_METRIC_WEIGHT", 1.0)
NATURAL_LINGUISTIC_METRIC_WEIGHT: float = _get_float("NATURAL_LINGUISTIC_METRIC_WEIGHT", 0.92)
NATURAL_ACOUSTIC_METRIC_WEIGHT: float = _get_float("NATURAL_ACOUSTIC_METRIC_WEIGHT", 0.78)
PROFILE_STYLE_LEAK_MIN: float = _get_float("PROFILE_STYLE_LEAK_MIN", 0.10)
FLUENT_STYLE_LEAK_FACTOR: float = _get_float("FLUENT_STYLE_LEAK_FACTOR", 0.85)
FLUENT_STYLE_LEAK_DAMPEN_MAX: float = _get_float("FLUENT_STYLE_LEAK_DAMPEN_MAX", 0.38)
COGNITIVE_TURBULENCE_WOBBLE_MIN: float = _get_float("COGNITIVE_TURBULENCE_WOBBLE_MIN", 0.14)
COGNITIVE_TURBULENCE_REPAIR_MIN: float = _get_float("COGNITIVE_TURBULENCE_REPAIR_MIN", 0.16)
COGNITIVE_TURBULENCE_SPONTANEITY_MIN: float = _get_float(
    "COGNITIVE_TURBULENCE_SPONTANEITY_MIN", 0.38
)
COGNITIVE_TURBULENCE_SCRIPT_DAMPEN: float = _get_float("COGNITIVE_TURBULENCE_SCRIPT_DAMPEN", 0.22)
COGNITIVE_TURBULENCE_SCRIPT_DAMPEN_MAX: float = _get_float(
    "COGNITIVE_TURBULENCE_SCRIPT_DAMPEN_MAX", 0.28
)

# --- Fluent NATURAL profile learning (broader spontaneous anchors) ---
ENABLE_FLUENT_NATURAL_PROFILE_LEARNING: bool = _get_bool(
    "ENABLE_FLUENT_NATURAL_PROFILE_LEARNING", True
)
FLUENT_NATURAL_UPDATE_SCRIPT_CEILING: float = _get_float(
    "FLUENT_NATURAL_UPDATE_SCRIPT_CEILING", 0.62
)
FLUENT_NATURAL_LEARNING_MIN_SPONTANEITY: float = _get_float(
    "FLUENT_NATURAL_LEARNING_MIN_SPONTANEITY", 0.40
)
FLUENT_NATURAL_LEARNING_STRONG_SPONTANEITY: float = _get_float(
    "FLUENT_NATURAL_LEARNING_STRONG_SPONTANEITY", 0.48
)
FLUENT_NATURAL_LEARNING_MAX_GUIDED: float = _get_float(
    "FLUENT_NATURAL_LEARNING_MAX_GUIDED", 0.58
)
FLUENT_NATURAL_LEARNING_MIN_NATURALITY: float = _get_float(
    "FLUENT_NATURAL_LEARNING_MIN_NATURALITY", 0.42
)
FLUENT_NATURAL_LEARNING_MIN_TURBULENCE: float = _get_float(
    "FLUENT_NATURAL_LEARNING_MIN_TURBULENCE", 0.22
)
FLUENT_NATURAL_MIN_PAUSE_ENTROPY: float = _get_float("FLUENT_NATURAL_MIN_PAUSE_ENTROPY", 0.42)
FLUENT_NATURAL_MIN_PITCH_DELTA: float = _get_float("FLUENT_NATURAL_MIN_PITCH_DELTA", 8.0)
FLUENT_NATURAL_LEARNING_CONFIDENCE: float = _get_float(
    "FLUENT_NATURAL_LEARNING_CONFIDENCE", 0.58
)

# --- Rehearsed vs live-guided cognition separation ---
REHEARSAL_PROTECTION_MIN_SPONTANEITY: float = _get_float(
    "REHEARSAL_PROTECTION_MIN_SPONTANEITY", 0.34
)
REHEARSAL_PROTECTION_MAX_GUIDED: float = _get_float(
    "REHEARSAL_PROTECTION_MAX_GUIDED", 0.62
)
REHEARSAL_PROTECTION_MIN_TURBULENCE: float = _get_float(
    "REHEARSAL_PROTECTION_MIN_TURBULENCE", 0.20
)
REHEARSAL_PROTECTION_MIN_RECOVERY: float = _get_float(
    "REHEARSAL_PROTECTION_MIN_RECOVERY", 0.12
)
REHEARSAL_PROTECTION_MAX_STABILITY: float = _get_float(
    "REHEARSAL_PROTECTION_MAX_STABILITY", 0.76
)
GUIDANCE_DOMINANCE_MIN_PROBABLE: float = _get_float(
    "GUIDANCE_DOMINANCE_MIN_PROBABLE", 0.58
)
GUIDANCE_DOMINANCE_STRICT_FOR_WEAK: float = _get_float(
    "GUIDANCE_DOMINANCE_STRICT_FOR_WEAK", 0.66
)
PREPARED_BEHAVIOR_SOFTEN_TO_AMBIGUOUS: bool = _get_bool(
    "PREPARED_BEHAVIOR_SOFTEN_TO_AMBIGUOUS", True
)
SEMANTIC_GUIDEDNESS_MIN_PROBABLE: float = _get_float(
    "SEMANTIC_GUIDEDNESS_MIN_PROBABLE", 0.54
)
ESSAY_LIKE_GUIDEDNESS_MIN: float = _get_float(
    "ESSAY_LIKE_GUIDEDNESS_MIN", 0.46
)
GENERALIZATION_CONSENSUS_MIN_SCORE: float = _get_float(
    "GENERALIZATION_CONSENSUS_MIN_SCORE", 0.56
)
GENERALIZATION_DIVERSITY_MIN_SIGNALS: int = int(
    _get_float("GENERALIZATION_DIVERSITY_MIN_SIGNALS", 4)
)
GENERALIZATION_SAFETY_MAX_HUMAN_VARIABILITY: float = _get_float(
    "GENERALIZATION_SAFETY_MAX_HUMAN_VARIABILITY", 0.58
)
GENERALIZATION_ENABLE_UNCERTAINTY_PRESERVE: bool = _get_bool(
    "GENERALIZATION_ENABLE_UNCERTAINTY_PRESERVE", True
)
SEMANTIC_EFFORT_DECOUPLING_PROBABLE_MIN: float = _get_float(
    "SEMANTIC_EFFORT_DECOUPLING_PROBABLE_MIN", 0.58
)
SEMANTIC_ACOUSTIC_COHERENCE_CLEAR_MIN: float = _get_float(
    "SEMANTIC_ACOUSTIC_COHERENCE_CLEAR_MIN", 0.56
)
PRETOKEN_ADAPTATION_CLEAR_MIN: float = _get_float(
    "PRETOKEN_ADAPTATION_CLEAR_MIN", 0.42
)

# Cognitive Sourcing Inference — internal vs externally guided cognition
ENABLE_COGNITIVE_SOURCING: bool = _get_bool("ENABLE_COGNITIVE_SOURCING", True)
PREPARED_INTERNALIZATION_PROTECTION: bool = _get_bool(
    "PREPARED_INTERNALIZATION_PROTECTION", True
)
SOURCING_LIKELIHOOD_MARGIN: float = _get_float("SOURCING_LIKELIHOOD_MARGIN", 0.08)
SOURCING_SOFT_EVIDENCE_MIN: float = _get_float("SOURCING_SOFT_EVIDENCE_MIN", 0.38)
SOURCING_PROTECTION_WEAKEN_UNIFORM_MIN: float = _get_float(
    "SOURCING_PROTECTION_WEAKEN_UNIFORM_MIN", 0.62
)
SOURCING_PROTECTION_WEAKEN_COV_MAX: float = _get_float(
    "SOURCING_PROTECTION_WEAKEN_COV_MAX", 0.42
)
SOURCING_PROTECTION_WEAKEN_RETRIEVAL_MAX: float = _get_float(
    "SOURCING_PROTECTION_WEAKEN_RETRIEVAL_MAX", 0.35
)
SOURCING_EXTERNAL_PROMOTE_MIN: float = _get_float("SOURCING_EXTERNAL_PROMOTE_MIN", 0.52)
SOURCING_INTERNAL_CLEAR_MIN: float = _get_float("SOURCING_INTERNAL_CLEAR_MIN", 0.58)
SESSION_EXTERNAL_LIKELIHOOD_PROBABLE_MIN: float = _get_float(
    "SESSION_EXTERNAL_LIKELIHOOD_PROBABLE_MIN", 0.55
)
SESSION_EXTERNAL_LIKELIHOOD_AMBIGUOUS_MIN: float = _get_float(
    "SESSION_EXTERNAL_LIKELIHOOD_AMBIGUOUS_MIN", 0.45
)
SESSION_INTERNAL_LIKELIHOOD_CLEAR_MIN: float = _get_float(
    "SESSION_INTERNAL_LIKELIHOOD_CLEAR_MIN", 0.58
)
SESSION_UNIFORMITY_PROMOTE_MIN: float = _get_float(
    "SESSION_UNIFORMITY_PROMOTE_MIN", 0.52
)
ANSWER_EXTERNAL_LIKELIHOOD_PROMOTE_MIN: float = _get_float(
    "ANSWER_EXTERNAL_LIKELIHOOD_PROMOTE_MIN", 0.48
)

# Skip pyannote for calibration (single speaker reading) — saves ~30-90s
FAST_CALIBRATION: bool = _get_bool("FAST_CALIBRATION", True)
SKIP_DIARIZATION_CALIBRATION: bool = _get_bool("SKIP_DIARIZATION_CALIBRATION", True)

# Smaller Whisper for calibration only (interview still uses WHISPER_MODEL_SIZE)
WHISPER_CALIBRATION_MODEL_SIZE: str = _get_str("WHISPER_CALIBRATION_MODEL_SIZE", "tiny")
# Skip wav2vec alignment during calibration (faster; word times less precise)
WHISPER_SKIP_ALIGN_CALIBRATION: bool = _get_bool("WHISPER_SKIP_ALIGN_CALIBRATION", True)
# Skip wav2vec alignment during interview local ASR (saves ~1-3s per answer on CPU)
WHISPER_SKIP_ALIGN_INTERVIEW: bool = _get_bool("WHISPER_SKIP_ALIGN_INTERVIEW", True)
# Skip slow whisper-timestamped re-transcription when fillers are missing
WHISPER_DISABLE_FILLER_FALLBACK: bool = _get_bool("WHISPER_DISABLE_FILLER_FALLBACK", False)
# Preload pyannote diarization at web startup (avoids first-job load delay)
PRELOAD_DIARIZATION_ON_STARTUP: bool = _get_bool("PRELOAD_DIARIZATION_ON_STARTUP", True)

# Video timeline FPS (calibration can use lower FPS)
VIDEO_TIMELINE_FPS: float = _get_float("VIDEO_TIMELINE_FPS", 10.0)
VIDEO_CALIBRATION_FPS: float = _get_float("VIDEO_CALIBRATION_FPS", 5.0)

# Preload Whisper when web server starts (first job avoids 30-60s model load)
PRELOAD_MODELS_ON_STARTUP: bool = _get_bool("PRELOAD_MODELS_ON_STARTUP", True)
# When true, startup only loads the small calibration Whisper (interview model loads on first analyze)
PRELOAD_CALIBRATION_MODEL_ONLY: bool = _get_bool("PRELOAD_CALIBRATION_MODEL_ONLY", True)
# Optional Kaggle /calibrate (duplicates local work; large-v3+align on GPU). Off by default for speed.
KAGGLE_OFFLOAD_CALIBRATION: bool = _get_bool("KAGGLE_OFFLOAD_CALIBRATION", False)
KAGGLE_CALIBRATE_CONNECT_TIMEOUT_SEC: float = _get_float(
    "KAGGLE_CALIBRATE_CONNECT_TIMEOUT_SEC", 8.0
)
CALIBRATION_WINDOW_PARALLEL_WORKERS: int = max(
    1, int(_get_float("CALIBRATION_WINDOW_PARALLEL_WORKERS", 4))
)

# Kaggle GPU offload — skip slow local Whisper when notebook is configured
KAGGLE_CALIBRATE_TIMEOUT_SEC: int = int(_get_float("KAGGLE_CALIBRATE_TIMEOUT_SEC", 90))
KAGGLE_OFFLOAD: bool = _get_bool("KAGGLE_OFFLOAD", bool(KAGGLE_GPU_URL))
KAGGLE_OFFLOAD_TRANSCRIPTION: bool = _get_bool("KAGGLE_OFFLOAD_TRANSCRIPTION", True)
KAGGLE_PARALLEL_ANSWERS: int = max(1, int(_get_float("KAGGLE_PARALLEL_ANSWERS", 4)))
SKIP_LOCAL_WHISPER_WHEN_KAGGLE: bool = _get_bool("SKIP_LOCAL_WHISPER_WHEN_KAGGLE", True)
# Local pyannote diarization is more reliable for AI vs candidate — default off.
KAGGLE_OFFLOAD_SEGMENTATION: bool = _get_bool("KAGGLE_OFFLOAD_SEGMENTATION", False)
KAGGLE_SEGMENT_TIMEOUT_SEC: int = int(_get_float("KAGGLE_SEGMENT_TIMEOUT_SEC", 900))
# fast = Silero VAD + long-turn filter (~10–30s); pyannote = accurate but slow (minutes)
KAGGLE_SEGMENT_MODE: str = _get_str("KAGGLE_SEGMENT_MODE", "pyannote").lower()
KAGGLE_FAST_MIN_CANDIDATE_SEC: float = _get_float("KAGGLE_FAST_MIN_CANDIDATE_SEC", 3.0)
KAGGLE_SKIP_ALIGN_INTERVIEW: bool = _get_bool("KAGGLE_SKIP_ALIGN_INTERVIEW", True)
# When true, prefetch uses /transcribe_answer only (faster than /analyze_batch per answer)
KAGGLE_TRANSCRIBE_ONLY: bool = _get_bool("KAGGLE_TRANSCRIBE_ONLY", False)
VIDEO_INTERVIEW_FPS: float = _get_float("VIDEO_INTERVIEW_FPS", 5.0)
AUDIO_WINDOW_PARALLEL_WORKERS: int = max(
    1, int(_get_float("AUDIO_WINDOW_PARALLEL_WORKERS", 4))
)

# --- Interview speaker selection (pyannote diarization) ---
# most_speech   — speaker with highest total talk time (legacy; pre-Kaggle default)
# least_speech  — speaker with least talk time (AI interviewer talks more)
# longest_turns — longer median turns (can mis-pick if candidate gives short answers)
# auto          — vote + composite (recommended)
_CANDIDATE_SPEAKER_RAW = _get_str("CANDIDATE_SPEAKER", "auto").lower()
if _CANDIDATE_SPEAKER_RAW not in ("most_speech", "least_speech", "longest_turns", "auto"):
    _CANDIDATE_SPEAKER_RAW = "auto"
CANDIDATE_SPEAKER: str = _CANDIDATE_SPEAKER_RAW

# Only used for longest_turns: ignore turns shorter than this when scoring speakers
CANDIDATE_TURN_MIN_SEC: float = _get_float("CANDIDATE_TURN_MIN_SEC", 3.0)
# Drop candidate-track segments shorter than this (mis-labeled AI prompts)
MIN_CANDIDATE_SEGMENT_SEC: float = _get_float("MIN_CANDIDATE_SEGMENT_SEC", 4.0)
AI_SHORT_TURN_SEC: float = _get_float("AI_SHORT_TURN_SEC", 2.5)
DIARIZATION_NUM_SPEAKERS: int = max(2, int(_get_float("DIARIZATION_NUM_SPEAKERS", 2)))
